"""messages字段更新

Revision ID: ee6fda53681d
Revises: 2a1ba2b9db7b
Create Date: 2026-05-25 11:37:30.110424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6fda53681d'
down_revision: Union[str, None] = '2a1ba2b9db7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('model_answer', sa.Text(), nullable=False))
    op.drop_column('messages', 'model_question')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('model_question', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'model_answer')
    # ### end Alembic commands ###
